### ISSUE TITLE
加解密的秘钥怎么获取？

### ISSUE THREAD

**Issue by bqingAll** [zhuojl/mybatis-crypt#1]

**Comment by zhuojl** [comment]
直接loadProperties？
你是和spring融合使用把？其实handler都是单例，在CryptHandlerFactory 中是new创建的静态变量，如果你结合spring用的话，就把handler作为普通单例的bean就行了，需要注入什么属性就随便注入就可以了。

**Comment by bqingAll** [comment]
嗯 用的Properties去加载
